/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_absence_chiara_MoodLed_LEDManager */

#ifndef _Included_com_absence_chiara_MoodLed_LEDManager
#define _Included_com_absence_chiara_MoodLed_LEDManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_absence_chiara_MoodLed_LEDManager
 * Method:    switchOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_absence_chiara_MoodLed_LEDManager_switchOff
  (JNIEnv *, jclass);

/*
 * Class:     com_absence_chiara_MoodLed_LEDManager
 * Method:    switchOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_absence_chiara_MoodLed_LEDManager_switchOn
  (JNIEnv *, jclass);

/*
 * Class:     com_absence_chiara_MoodLed_LEDManager
 * Method:    setRGB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_absence_chiara_MoodLed_LEDManager_setRGB
  (JNIEnv *, jclass);

/*
 * Class:     com_absence_chiara_MoodLed_LEDManager
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_absence_chiara_MoodLed_LEDManager_init
  (JNIEnv *, jclass);

/*
 * Class:     com_absence_chiara_MoodLed_LEDManager
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_absence_chiara_MoodLed_LEDManager_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
